#!/usr/bin/env bash

echo "NAME=linux-x64-glibc
NODE_ARCH=x64
NODE_OS=linux
NODE_PKG_NAME=syncpack-linux-x64
OS=ubuntu-22.04
TARGET=x86_64-unknown-linux-gnu
RUST_BINARY_PATH=\"target/\${TARGET}/release/syncpack\"
NODE_PKG_DIR_PATH=\"npm/packages/\${NODE_PKG_NAME}\"
NODE_PKG_RUST_BINARY_PATH=\"\${NODE_PKG_DIR_PATH}/bin/syncpack\"
NODE_ROOT_PKG_DIR_PATH=npm/packages/syncpack" > .env.linux-x64-glibc
echo "NAME=linux-arm64-glibc
NODE_ARCH=arm64
NODE_OS=linux
NODE_PKG_NAME=syncpack-linux-arm64
OS=ubuntu-22.04
TARGET=aarch64-unknown-linux-gnu
RUST_BINARY_PATH=\"target/\${TARGET}/release/syncpack\"
NODE_PKG_DIR_PATH=\"npm/packages/\${NODE_PKG_NAME}\"
NODE_PKG_RUST_BINARY_PATH=\"\${NODE_PKG_DIR_PATH}/bin/syncpack\"
NODE_ROOT_PKG_DIR_PATH=npm/packages/syncpack" > .env.linux-arm64-glibc
echo "NAME=win32-x64-msvc
NODE_ARCH=x64
NODE_OS=win32
NODE_PKG_NAME=syncpack-windows-x64
OS=windows-2022
TARGET=x86_64-pc-windows-msvc
RUST_BINARY_PATH=\"target/\${TARGET}/release/syncpack\"
NODE_PKG_DIR_PATH=\"npm/packages/\${NODE_PKG_NAME}\"
NODE_PKG_RUST_BINARY_PATH=\"\${NODE_PKG_DIR_PATH}/bin/syncpack\"
NODE_ROOT_PKG_DIR_PATH=npm/packages/syncpack" > .env.win32-x64-msvc
echo "NAME=win32-arm64-msvc
NODE_ARCH=arm64
NODE_OS=win32
NODE_PKG_NAME=syncpack-windows-arm64
OS=windows-2022
TARGET=aarch64-pc-windows-msvc
RUST_BINARY_PATH=\"target/\${TARGET}/release/syncpack\"
NODE_PKG_DIR_PATH=\"npm/packages/\${NODE_PKG_NAME}\"
NODE_PKG_RUST_BINARY_PATH=\"\${NODE_PKG_DIR_PATH}/bin/syncpack\"
NODE_ROOT_PKG_DIR_PATH=npm/packages/syncpack" > .env.win32-arm64-msvc
echo "NAME=darwin-x64
NODE_ARCH=x64
NODE_OS=darwin
NODE_PKG_NAME=syncpack-darwin-x64
OS=macos-13
TARGET=x86_64-apple-darwin
RUST_BINARY_PATH=\"target/\${TARGET}/release/syncpack\"
NODE_PKG_DIR_PATH=\"npm/packages/\${NODE_PKG_NAME}\"
NODE_PKG_RUST_BINARY_PATH=\"\${NODE_PKG_DIR_PATH}/bin/syncpack\"
NODE_ROOT_PKG_DIR_PATH=npm/packages/syncpack" > .env.darwin-x64
echo "NAME=darwin-arm64
NODE_ARCH=arm64
NODE_OS=darwin
NODE_PKG_NAME=syncpack-darwin-arm64
OS=macos-13
TARGET=aarch64-apple-darwin
RUST_BINARY_PATH=\"target/\${TARGET}/release/syncpack\"
NODE_PKG_DIR_PATH=\"npm/packages/\${NODE_PKG_NAME}\"
NODE_PKG_RUST_BINARY_PATH=\"\${NODE_PKG_DIR_PATH}/bin/syncpack\"
NODE_ROOT_PKG_DIR_PATH=npm/packages/syncpack" > .env.darwin-arm64
